language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install .
# don't check host keys -Â the tests need to access repos over ssh, which would
# otherwise stall asking about the server's fingerprint
before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e 'Host bitbucket.org\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
  - ssh-keygen -t rsa -C "test@yottabuild.org" -f ~/.ssh/id_rsa -N ""
# command to run tests
script: python setup.py test 
